services:
  video-service :
    container_name : video-service
    image : video-service:latest
    tty : True
    command : ["bash"]
  
  openface-service : 
    container_name: openface-service
    image: openface-service:latest
    tty: true
    privileged: true
    volumes:
    #   - "${DATA_MOUNT}:${DATA_MOUNT}"
    #   - ./:/workspace
      - /dev/video0:/dev/video0
    # ports:
    #   - "8081:8081"
    # environment:
    #   DATA_MOUNT: "${DATA_MOUNT}"
    command: ["bash"]