services:
  decision-service:
    image: decision-service:latest
    ports:
      - "8083:8083"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8083"]


  # openface-service : 
  #   container_name: openface-service
  #   image : openface-service:latest
  #   tty: true
  #   command: ["bash"]